news/urls.py
from django.conf.urls import patterns, url
from news import views

urlpatterns = patterns('',
	url(r'^$',views.Index.as_view(),name='index'),
	url(r'^add/$',views.Add.as_view(),name='add'),
	url(r'^(?P<pk>\d+)/update/$',views.Update.as_view(),name='update'),
	url(r'^(?P<pk>\d+)/delete/$',views.Delete.as_view(),name='delete'),
	url(r'^(?P<pk>\d+)/$',views.Detail.as_view(),name='detail'),
)

projectManager/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'projectManager.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'projectManager.views.home', name='home'),
    url(r'^logout/', 'projectManager.views.logout_view', name='logout'),
    url(r'^login/', 'projectManager.views.login_view', name='login'),
    url(r'^contact/', 'projectManager.views.contact', name='contact'),
    url(r'^send_contact/', 'projectManager.views.send_contact', name='send_contact'),
    url(r'^about/', 'projectManager.views.about', name='about'),
    url(r'^news/',include('news.urls', namespace='news')),
    url(r'^videos/',include('videos.urls', namespace='videos')),
    url(r'^projects/',include('projects.urls', namespace='projects')),
    url(r'^admin/', include(admin.site.urls)),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    #url(r'^$', 'projectManager.views.home', name='home'),
    # url(r'^projectManager/', include('projectManager.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^$', include('home.urls', namespace="home")),
    url(r'^projects/', include('projects.urls', namespace="projects")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^upload/', include('files.urls')),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
from django.db import models

class New(models.Model):
	title = models.CharField(max_length=100)
	portrait = models.CharField(max_length=250)
	description = models.TextField()
	pub_date = models.DateTimeField('date published')

	def __unicode__(self):
		return self.title

news/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView, ListView
from django.core.urlresolvers import reverse_lazy
from news.models import New

class Index (ListView):
	template_name = 'news/index.html'
	context_object_name = 'newsList'
	def get_queryset(self):
		return New.objects.order_by('-pub_date')

class Detail(DetailView):
	model = New
	template_name = 'news/detail.html'

class Add(CreateView):
	model = New
	success_url = reverse_lazy('news:index')

class Update(UpdateView):
	model = New
	field = ['title','description']

class Delete(DeleteView):
	model = New
	success_url = reverse_lazy('news:index')

news/templates/news/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block header %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/detail.css' %}">
{% endblock%}
{% block content %}
  <h1>{{new.title}}</h1>
  <div>
  	<div class='header'>
  		<img src="{{new.portrait}}" style="max-height:300px">
  	</div>
  	<div >
  		<p class="text-muted">
			{{new.description}}
 		</p>
  	</div>
  </div>
{% endblock %}

news/templates/news/index.html
{% extends 'base.html' %}
{% block title %}- News{% endblock %}
{% block content %}
	<h2>News</h2>
	{% if perms.news.add_new %}
		<div><a href="{% url 'news:add'  %}" class="">Add new</a></div>
	{% endif %}
	{% include 'news/list.html' %}
{% endblock %}

news/templates/news/list.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}">
{% if newsList %}
		<div class="row">
		{% for new in newsList %}
			<div class="col-lg-3">
				<div class="thumbnail">
					<img data-src="holder.js/100%x180" alt="100%x180" src="{{ new.portrait }}">
					<div class="caption">
						<h3>{{ new.title }}</h3>
						<p class="description">{{ new.description }}</p>
						<p><a href="{% url 'news:detail' new.pk %}" class="btn btn-primary" role="button">Read more</a></p>
					</div>
				</div>
			</div>
		{% endfor %}
		</div>
	{% else %}
		<p>No news are available.</p>
	{% endif %}

news/templates/news/new_confirm_delete.html
<form action="" method="post">{% csrf_token %}
	<p>Are you sure you want to delete "{{ object }}"?</p>
	<input type="submit" value="Confirm" />
</form>

news/templates/news/new_form.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Create" />
</form>
{% endblock %}