home/urls.py
from django.conf.urls.defaults import patterns, url
from home import views

urlpatterns = patterns('',
	url(r'^$',views.index,name='index'),
)

projectManager/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'projectManager.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'projectManager.views.home', name='home'),
    url(r'^logout/', 'projectManager.views.logout_view', name='logout'),
    url(r'^login/', 'projectManager.views.login_view', name='login'),
    url(r'^contact/', 'projectManager.views.contact', name='contact'),
    url(r'^send_contact/', 'projectManager.views.send_contact', name='send_contact'),
    url(r'^about/', 'projectManager.views.about', name='about'),
    url(r'^news/',include('news.urls', namespace='news')),
    url(r'^videos/',include('videos.urls', namespace='videos')),
    url(r'^projects/',include('projects.urls', namespace='projects')),
    url(r'^admin/', include(admin.site.urls)),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    #url(r'^$', 'projectManager.views.home', name='home'),
    # url(r'^projectManager/', include('projectManager.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^$', include('home.urls', namespace="home")),
    url(r'^projects/', include('projects.urls', namespace="projects")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^upload/', include('files.urls')),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectManager/views.py
from django.shortcuts import render
from projects.models import Project
from news.models import New
from videos.models import Video
from django.contrib.auth import logout, authenticate, login
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.mail import send_mail

def home(request):
	projectsList = Project.objects.all().order_by('-pub_date')[:4]
	newsList = New.objects.all().order_by('-pub_date')[:4]
	videosList = Video.objects.all().order_by('-pub_date')[:4]
	context = {'projectsList': projectsList,'newsList':newsList,'videosList':videosList}
	return render(request, 'projectManager/home.html', context)

def contact(request):
	if request.method == 'GET':
		return render(request, 'projectManager/contact.html')
	else:
		asunto = request.POST.get('asunto_txt')
		mensaje = request.POST.get('mensaje_txa')
		nombre = request.POST.get('nombre_txt')
		telefono = request.POST.get('telefono_txt')
		email = request.PoST.get('email_txt')

		send_mail(asunto, mensaje, email,
    	['info@imasdottokrause.com.ar'], fail_silently=False)
		return HttpResponseRedirect(reverse('home'))

def about(request):
	return render(request, 'projectManager/about.html')

def send_contact(request):
	return HttpResponseRedirect(reverse('home'))

def login_view(request):
	username = request.POST['username']
	password = request.POST['password']
	user = authenticate(username=username, password=password)
	if user is not None:
		if user.is_active:
			login(request, user)
			return HttpResponseRedirect(reverse('home'))
		else:
			return HttpResponseRedirect(reverse('home'))
	else:
		return HttpResponseRedirect(reverse('home'))

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

projectManager/templates/base.html
{% load staticfiles %}
<html>
	<head>
	<title>Usina J. Newbery {% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/screen.css' %}" media='screen'>
	<link rel="stylesheet" type="text/css" href="{% static 'css/print.css' %}" media='screen'>
	<!--[if IE]>
		<link rel="stylesheet" type="text/css" href="{% static 'css/ie.css' %}" media='screen'>
	<![endif]-->
	<script src="{% static 'js/jquery-1.10.2.js' %}"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
	<script src="{% static 'js/bootstrap.js' %}" ></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
	{% block header %}{% endblock %}
	</head>
	<body>
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<a class="navbar-brand" href="{% url 'home' %}">Usina J. Newberry</a>
			<ul class="nav navbar-nav navbar-right">
				<li><a href="{% url 'projects:index'  %}">Projects</a></li>
				<li><a href="{% url 'news:index'  %}">News</a></li>
				<li><a href="{% url 'videos:index'  %}">Videos</a></li>
				<li><a href="{% url 'about'  %}">About</a></li>
				<li><a href="{% url 'contact'  %}">Contact</a></li>
				{% if user.is_authenticated %}
					<li><a href="{% url 'logout'  %}" class="">Logout</a></li>
				{% else %}
					<form class="navbar-form navbar-left" method="post" action="{% url 'login' %}">{% csrf_token %}
						<div class="form-group">
							<input type="text" class="form-control" placeholder="Username" name="username">
						</div>
						<div class="form-group">
							<input type="password" class="form-control" placeholder="Password" name="password">
						</div>
						<button type="submit" class="btn btn-default">Login</button>
					</form>
				{% endif %}
			</ul>
		</div>
	</nav>
	<div class='container'>
		{% block content %}{% endblock %}
		<p><hr></p>

		<footer class="row">
			<div class="span6">
			<p><a href="https://github.com/dyve/django-bootstrap-toolkit">Usina J. Newberry</a></p>
			</div>
			<div class="span6" style="text-align:right">
			<p>
			    &copy; <a href="http://twitter.com/dyve">Denys Bulavka</a>
			</p>
			</div>
		</footer>
    </div>
	</body>
</html>