projectManager/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'projectManager.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'projectManager.views.home', name='home'),
    url(r'^logout/', 'projectManager.views.logout_view', name='logout'),
    url(r'^login/', 'projectManager.views.login_view', name='login'),
    url(r'^contact/', 'projectManager.views.contact', name='contact'),
    url(r'^send_contact/', 'projectManager.views.send_contact', name='send_contact'),
    url(r'^about/', 'projectManager.views.about', name='about'),
    url(r'^news/',include('news.urls', namespace='news')),
    url(r'^videos/',include('videos.urls', namespace='videos')),
    url(r'^projects/',include('projects.urls', namespace='projects')),
    url(r'^admin/', include(admin.site.urls)),
)

projects/urls.py
from django.conf.urls import patterns, url
from projects import views

urlpatterns = patterns('',
	url(r'^$',views.Index.as_view(),name='index'),
	url(r'^add/$',views.Add.as_view(),name='add'),
	url(r'^(?P<pk>\d+)/update/$',views.Update.as_view(),name='update'),
	url(r'^(?P<pk>\d+)/delete/$',views.Delete.as_view(),name='delete'),
	url(r'^(?P<pk>\d+)/$',views.Detail.as_view(),name='detail'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    #url(r'^$', 'projectManager.views.home', name='home'),
    # url(r'^projectManager/', include('projectManager.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^$', include('home.urls', namespace="home")),
    url(r'^projects/', include('projects.urls', namespace="projects")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^upload/', include('files.urls')),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
	title = models.CharField(max_length=100)
	description = models.TextField()
	portrait = models.CharField(max_length=250)
	repository = models.CharField(max_length=250)
	pub_date = models.DateTimeField('date published')

	def __unicode__(self):
		return self.title

# class Picture(models.Model):
# 	project = models.ForeignKey(Project)
# 	title = models.CharField(max_length=50)
# 	file  = models.FileField(upload_to='projects')

projects/forms.py
from django.forms import ModelForm
from projects.models import Project, Picture
from django.forms.models import inlineformset_factory

class ProjectForm(ModelForm):
	class Meta:
		model = Project

#class PictureForm(ModelForm):
#	class Meta:
#		model = Picture
#		exclude = ('project',)

#PictureFormSet = inlineformset_factory(Project, Picture)

projects/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView, ListView
from django.core.urlresolvers import reverse_lazy
from projects.models import Project

class Index (ListView):
	template_name = 'projects/index.html'
	context_object_name = 'projectsList'
	def get_queryset(self):
		return Project.objects.order_by('-pub_date')

class Detail(DetailView):
	model = Project
	template_name = 'projects/detail.html'

class Add(CreateView):
	model = Project
	success_url = reverse_lazy('projects:index')

class Update(UpdateView):
	model = Project
	field = ['title','description']

class Delete(DeleteView):
	model = Project
	success_url = reverse_lazy('projects:index')

projects/templates/projects/create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block header %}
	<script type="text/javascript" src="{% static 'js/jquery.formset.js' %}"></script>
	<script type="text/javascript">
		$(function() {
            $(".inline.{{ picture_form.prefix }}").formset({
                prefix: "{{ picture_form.prefix }}",
            })
        })
	</script>
{% endblock %}
{% block content %}
<div>
        <h1>Add Project</h1>
        <form action="." method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                {{ form.as_p }}
            </div>
            <fieldset>
                <legend>Project pictures</legend>
                {{ picture_form.management_form }}
                {{ picture_form.non_form_errors }}
                {% for form in picture_form %}
                    {{ form.id }}
                    <div class="inline {{ picture_form.prefix }}">
                        {{ form.as_p }}
                    </div>
                {% endfor %}
            </fieldset>
            <input type="submit" value="Add project" class="submit" />
        </form>
    </div>
{% endblock %}

projects/templates/projects/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block header %}
	<script type="text/javascript" src="{% static 'js/jquery.rss.js' %}"></script>
	<script type="text/javascript">
		jQuery(function($) {
        $("#rss-feeds").rss("{{ project.repository }}/rss");
        $("#repository").click(function(){window.location.href = '{{ project.repository }}';});
      })
	</script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/detail.css' %}">
{% endblock %}
{% block content %}
  <h1>{{project.title}}</h1>
  <div>
  	<div class='header'>
  		<img src="{{project.portrait}}" style="max-height:300px">
  	</div>
  	<div >
  		<p class="text-muted">
			{{project.description}}
 		</p>
  	</div>
  </div>
  <div class='clear'></div> 
<button type="button" class="btn btn-info" id="repository">Repository</button>
<div id="rss-feeds"></div>
{% endblock %}

projects/templates/projects/index.html
{% extends 'base.html' %}
{% block title %}- Projects{% endblock %}
{% block content %}
	<h2>Projects</h2>
	{% if perms.projects.add_project %}
		<div><a href="{% url 'projects:add'  %}" class="">Add project</a></div>
	{% endif %}
	{% include 'projects/list.html' %}
{% endblock %}

projects/templates/projects/list.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}">
{% if projectsList %}
		<div class="row">
		{% for project in projectsList %}
			<div class="col-lg-3">
				<div class="thumbnail">
					<img data-src="holder.js/100%x180" alt="100%x180" src="{{ project.portrait }}">
					<div class="caption">
						<h3>{{ project.title }}</h3>
						<p class="description">{{ project.description }}</p>
						<p><a href="{% url 'projects:detail' project.pk %}" class="btn btn-primary" role="button">Read more</a></p>

					</div>
				</div>
			</div>
		{% endfor %}
		</div>
	{% else %}
		<p>No projects are available.</p>
	{% endif %}

projects/templates/projects/project.html
{% extends  "home/base.html"%}
{% load url from future %}
{% load static %}

{% block content %}
	{% if project %}
		<h1>Name: {{project.name}}</h1>
		<h3>Repository: {{project.repository}}</h3>
		<div class="well">
			Description: {{project.description}}
		</div>
	{% endif %}
	{% if documents %}
        <div class="row">
        {% for document in documents %}
        	<div class="col-lg-3">
				<a href="#" class="thumbnail">
					<img data-src="holder.js/100%x180" alt="" src="{{ document.docfile.url }}">
				</a>
			</div>
        {% endfor %}
        </div>
    {% else %}
        <p>No documents.</p>
    {% endif %}

        <!-- Upload form. Note enctype attribute! -->
        <form action="." method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>
            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>
            <p>
                {{ form.docfile.errors }}
                {{ form.docfile }}
            </p>
            <p><input type="submit" value="Upload" /></p>
        </form>
{% endblock %}

projects/templates/projects/project_confirm_delete.html
<form action="" method="post">{% csrf_token %}
	<p>Are you sure you want to delete "{{ object }}"?</p>
	<input type="submit" value="Confirm" />
</form>

projects/templates/projects/project_form.html
{% extends 'base.html' %}
{% block title %}- Add project{% endblock %}
{% block content %}
<form action="" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Create" />
</form>
{% endblock %}