projectManager/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'projectManager.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'projectManager.views.home', name='home'),
    url(r'^logout/', 'projectManager.views.logout_view', name='logout'),
    url(r'^login/', 'projectManager.views.login_view', name='login'),
    url(r'^contact/', 'projectManager.views.contact', name='contact'),
    url(r'^send_contact/', 'projectManager.views.send_contact', name='send_contact'),
    url(r'^about/', 'projectManager.views.about', name='about'),
    url(r'^news/',include('news.urls', namespace='news')),
    url(r'^videos/',include('videos.urls', namespace='videos')),
    url(r'^projects/',include('projects.urls', namespace='projects')),
    url(r'^admin/', include(admin.site.urls)),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    #url(r'^$', 'projectManager.views.home', name='home'),
    # url(r'^projectManager/', include('projectManager.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^$', include('home.urls', namespace="home")),
    url(r'^projects/', include('projects.urls', namespace="projects")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^upload/', include('files.urls')),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

videos/urls.py
from django.conf.urls import patterns, url
from videos import views

urlpatterns = patterns('',
	url(r'^$',views.Index.as_view(),name='index'),
	url(r'^add/$',views.Add.as_view(),name='add'),
	url(r'^(?P<pk>\d+)/update/$',views.Update.as_view(),name='update'),
	url(r'^(?P<pk>\d+)/delete/$',views.Delete.as_view(),name='delete'),
	url(r'^(?P<pk>\d+)/$',views.Detail.as_view(),name='detail'),
)

videos/models.py
from django.db import models

class Video(models.Model):
	title = models.CharField(max_length=100)
	description = models.TextField()
	portrait = models.CharField(max_length=250)
	pub_date = models.DateTimeField('date published')
	embedded = models.CharField(max_length=250)

	def __unicode__(self):
		return self.title

videos/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView, ListView
from django.core.urlresolvers import reverse_lazy
from videos.models import Video

class Index (ListView):
	template_name = 'videos/index.html'
	context_object_name = 'videosList'
	def get_queryset(self):
		return Video.objects.order_by('-pub_date')

class Detail(DetailView):
	model = Video
	template_name = 'videos/detail.html'

class Add(CreateView):
	model = Video
	success_url = reverse_lazy('videos:index')

class Update(UpdateView):
	model = Video
	field = ['title','description']

class Delete(DeleteView):
	model = Video
	success_url = reverse_lazy('videos:index')

videos/templates/videos/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block header %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/detail.css' %}">
{% endblock%}
{% block content %}
  <h1>{{video.title}}</h1>
  <div>
  	<div class='header'>
  		{% autoescape off %}
    		{{video.embedded}}
		{% endautoescape %}
  	</div>
  	<div >
  		<p class="text-muted">
			{{video.description}}
 		</p>
  	</div>
  </div>
{% endblock %}

videos/templates/videos/index.html
{% extends 'base.html' %}
{% block title %}- Videos{% endblock %}
{% block content %}
	<h2>Videos</h2>
	{% if perms.videos.add_video %}
		<div><a href="{% url 'videos:add'  %}" class="">Add video</a></div>
	{% endif %}
	{% include 'videos/list.html' %}
{% endblock %}

videos/templates/videos/list.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}">
{% if videosList %}
		<div class="row">
		{% for video in videosList %}
			<div class="col-lg-3">
				<div class="thumbnail">
					<img data-src="holder.js/100%x180" alt="100%x180" src="{{ video.portrait }}">
					<div class="caption">
						<h3>{{ video.title }}</h3>
						<p class='description'>{{ video.description }}</p>
						<p><a href="{% url 'videos:detail' video.pk %}" class="btn btn-primary" role="button">Read more</a></p>
					</div>
				</div>
			</div>
		{% endfor %}
		</div>
	{% else %}
		<p>No videos are available.</p>
	{% endif %}

videos/templates/videos/video_confirm_delete.html
<form action="" method="post">{% csrf_token %}
	<p>Are you sure you want to delete "{{ object }}"?</p>
	<input type="submit" value="Confirm" />
</form>

videos/templates/videos/video_form.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Create" />
</form>
{% endblock %}